feat: add useShortcuts #87
ChatGPT-Desktop/ChatGPT-Desktop pull request #88
Opened 2023-03-23 17:43 UTC by l1m2e

2023-03-23 22:03 UTC, orangelckc requested changes

2023-03-23 22:07 UTC, orangelckc commented on src/hooks/useShortcuts.ts
另外，是否考虑在首页显示这些按键提示信息 @bilibili-ayang 

有个小问题，mac上使用ctrl+l键时会有个黄色的闪烁，我不知道是不是我某个插件导致的

https://user-images.githubusercontent.com/48410934/227375306-896bb06a-6d81-4656-ac9f-66c7d0ab266b.mp4

2023-03-23 22:11 UTC, orangelckc commented
另外，是否考虑在首页显示这些按键提示信息 @bilibili-ayang 

有个小问题，mac上使用ctrl+l键时会有个黄色的闪烁，我不知道是不是我某个插件导致的

https://user-images.githubusercontent.com/48410934/227375306-896bb06a-6d81-4656-ac9f-66c7d0ab266b.mp4

2023-03-24 01:53 UTC, bilibili-ayang commented
@orangelckc 我测试是有这个问题，主要功能是高亮显示一下你当前选取的内容，safari 浏览器就有这个功能，直接加到禁用快捷键列表就可以！

2023-03-24 13:35 UTC, closed without merging